[versions]
java = "25"
paper = "26.1.2.build.60-stable"
junit = "6.0.3"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
