package fr.maxlego08.zauctionhouse.api.utils;

public enum Permission {

    ZAUCTIONHOUSE_USE,
    ZAUCTIONHOUSE_RELOAD,
    ZAUCTIONHOUSE_SELL,
    ZAUCTIONHOUSE_BID,
    ZAUCTIONHOUSE_RENT,
    ZAUCTIONHOUSE_ADMIN_REMOVE_INVENTORY("Allows access to the inventory to remove an item from the sale"),

    ZAUCTIONHOUSE_ADMIN,
    ZAUCTIONHOUSE_ADMIN_ITEMS;

    private final String description;
    private final String[] args;

    Permission() {
        this.description = "";
        this.args = new String[0];
    }

    Permission(String description, String... args) {
        this.description = description;
        this.args = args;
    }

    /**
     * Generates the permission string for this enum constant.
     * Converts the enum constant name to lowercase and replaces underscores with periods.
     *
     * @return The permission string.
     */
    public String asPermission() {
        return name().toLowerCase().replace("_", ".");
    }

    public String toPermission() {
        StringBuilder builder = new StringBuilder( asPermission());
        for (int i = 0; i < this.args.length; i++) {
            builder.append("<");
            builder.append(this.args[i]);
            builder.append(">");
            if (i < this.args.length - 1) {
                builder.append(".");
            }
        }
        return builder.toString();
    }

    /**
     * Generates a permission string for this enum constant with an additional suffix.
     * Appends the specified suffix to the permission string generated by {@link #asPermission()}.
     *
     * @param with The suffix to append.
     * @return The permission string with the suffix.
     */
    public String asPermission(String with) {
        return asPermission() + with;
    }

    public String getDescription() {
        return description;
    }

    public String[] getArgs() {
        return args;
    }

}